server:
  port: 80

spring:
  profiles:
    active: local
---

spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/information_schema
    username: root
    password: root
    platform: mysql

---

spring:
  profiles: dev
logging:
  config: src/main/resources/logback-back.xml
